### Continue to the previous notebook

In [1]:
import pandas as pd
import numpy as np
com = pd.read_csv(r'C:\BEPEC Python Material\Company_Data.csv')
com

Sales  CompPrice  Income  Advertising  Population  Price  Age  Education  \
0     9.50        138      73           11         276    120   42         17   
1    11.22        111      48           16         260     83   65         10   
2    10.06        113      35           10         269     80   59         12   
3     7.40        117     100            4         466     97   55         14   
4     4.15        141      64            3         340    128   38         13   
..     ...        ...     ...          ...         ...    ...  ...        ...   
395  12.57        138     108           17         203    128   33         14   
396   6.14        139      23            3          37    120   55         11   
397   7.41        162      26           12         368    159   40         18   
398   5.94        100      79            7         284     95   50         12   
399   9.71        134      37            0          27    120   49         16   

    Urban   US  
0     Yes  Yes  
1     Yes  Yes  
2     Yes  Yes  
3     Yes  Yes  
4     Yes   No  
..    ...  ...  
395   Yes  Yes  
396    No  Yes  
397   Yes  Yes  
398   Yes  Yes  
399   Yes  Yes  

[400 rows x 10 columns]

In [4]:
dates = pd.date_range('20010410', periods = 6)
dates

DatetimeIndex(['2001-04-10', '2001-04-11', '2001-04-12', '2001-04-13',
               '2001-04-14', '2001-04-15'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df = pd.DataFrame(np.random.randn(6,3), index = dates, columns = ['A','B','C'])
df

A         B         C
2001-04-10  1.528961 -0.110926 -1.181453
2001-04-11  0.511269  1.843507 -0.973316
2001-04-12  1.003140 -0.610323 -1.312590
2001-04-13 -0.198911 -1.170609 -0.449722
2001-04-14  0.285932 -0.453229 -1.484547
2001-04-15  1.639254  1.198057 -0.515530

In [22]:
# Selecting Data via Labels
df.loc[dates[0]:dates[2],['A','C']]

A         C
2001-04-10  1.528961 -1.181453
2001-04-11  0.511269 -0.973316
2001-04-12  1.003140 -1.312590

In [14]:
df.loc[dates[0]:dates[2],:]

A         B         C
2001-04-10  1.528961 -0.110926 -1.181453
2001-04-11  0.511269  1.843507 -0.973316
2001-04-12  1.003140 -0.610323 -1.312590

In [15]:
df.loc[dates[2],'C']

-1.312589608222182

In [18]:
# Selecting Data via Index
df.iloc[0:3,0]

2001-04-10    1.528961
2001-04-11    0.511269
2001-04-12    1.003140
Freq: D, Name: A, dtype: float64

In [20]:
df.iloc[0:3,:]

A         B         C
2001-04-10  1.528961 -0.110926 -1.181453
2001-04-11  0.511269  1.843507 -0.973316
2001-04-12  1.003140 -0.610323 -1.312590

In [24]:
df.iloc[[1,3],[0,2]]

A         C
2001-04-11  0.511269 -0.973316
2001-04-13 -0.198911 -0.449722

In [25]:
df

A         B         C
2001-04-10  1.528961 -0.110926 -1.181453
2001-04-11  0.511269  1.843507 -0.973316
2001-04-12  1.003140 -0.610323 -1.312590
2001-04-13 -0.198911 -1.170609 -0.449722
2001-04-14  0.285932 -0.453229 -1.484547
2001-04-15  1.639254  1.198057 -0.515530

In [26]:
# Bolean Indexing , are based on specific conditions
df[df['B']>0]

A         B         C
2001-04-11  0.511269  1.843507 -0.973316
2001-04-15  1.639254  1.198057 -0.515530

In [27]:
#Bolean Indexing
df[df>0]

A         B   C
2001-04-10  1.528961       NaN NaN
2001-04-11  0.511269  1.843507 NaN
2001-04-12  1.003140       NaN NaN
2001-04-13       NaN       NaN NaN
2001-04-14  0.285932       NaN NaN
2001-04-15  1.639254  1.198057 NaN

In [29]:
df2 = df.copy()
df2['D'] = ['one','two','three','one','four','three']
df2

A         B         C      D
2001-04-10  1.528961 -0.110926 -1.181453    one
2001-04-11  0.511269  1.843507 -0.973316    two
2001-04-12  1.003140 -0.610323 -1.312590  three
2001-04-13 -0.198911 -1.170609 -0.449722    one
2001-04-14  0.285932 -0.453229 -1.484547   four
2001-04-15  1.639254  1.198057 -0.515530  three

In [30]:
# Bolean indexing using isin() function.
df2[df2['D'].isin(['two','four'])]

A         B         C     D
2001-04-11  0.511269  1.843507 -0.973316   two
2001-04-14  0.285932 -0.453229 -1.484547  four

In [31]:
# Setings
s1 = pd.Series([1,2,3,4,5,6] , index = dates)
df2['E'] = s1
df2

A         B         C      D  E
2001-04-10  1.528961 -0.110926 -1.181453    one  1
2001-04-11  0.511269  1.843507 -0.973316    two  2
2001-04-12  1.003140 -0.610323 -1.312590  three  3
2001-04-13 -0.198911 -1.170609 -0.449722    one  4
2001-04-14  0.285932 -0.453229 -1.484547   four  5
2001-04-15  1.639254  1.198057 -0.515530  three  6

In [32]:
# Seting values by label
df2.at[dates[0],'A'] = 0
df2

A         B         C      D  E
2001-04-10  0.000000 -0.110926 -1.181453    one  1
2001-04-11  0.511269  1.843507 -0.973316    two  2
2001-04-12  1.003140 -0.610323 -1.312590  three  3
2001-04-13 -0.198911 -1.170609 -0.449722    one  4
2001-04-14  0.285932 -0.453229 -1.484547   four  5
2001-04-15  1.639254  1.198057 -0.515530  three  6

In [34]:
# Seting values by Position
df2.iat[0,0] = 1.528961
df2

A         B         C      D  E
2001-04-10  1.528961  1.528961 -1.181453    one  1
2001-04-11  0.511269  1.843507 -0.973316    two  2
2001-04-12  1.003140 -0.610323 -1.312590  three  3
2001-04-13 -0.198911 -1.170609 -0.449722    one  4
2001-04-14  0.285932 -0.453229 -1.484547   four  5
2001-04-15  1.639254  1.198057 -0.515530  three  6

In [37]:
# Seting values by assignning a Numpy array
df2.loc[:,'C'] = np.array([5]*len(df2), dtype = 'float32')
df2

A         B    C      D  E
2001-04-10  1.528961  1.528961  5.0    one  1
2001-04-11  0.511269  1.843507  5.0    two  2
2001-04-12  1.003140 -0.610323  5.0  three  3
2001-04-13 -0.198911 -1.170609  5.0    one  4
2001-04-14  0.285932 -0.453229  5.0   four  5
2001-04-15  1.639254  1.198057  5.0  three  6

In [40]:
# Creating a Numpy array
array = np.array([12,13]*5, dtype = 'int32')
array

array([12, 13, 12, 13, 12, 13, 12, 13, 12, 13])

In [41]:
df3 = df2.copy()
df3

A         B    C      D  E
2001-04-10  1.528961  1.528961  5.0    one  1
2001-04-11  0.511269  1.843507  5.0    two  2
2001-04-12  1.003140 -0.610323  5.0  three  3
2001-04-13 -0.198911 -1.170609  5.0    one  4
2001-04-14  0.285932 -0.453229  5.0   four  5
2001-04-15  1.639254  1.198057  5.0  three  6

In [45]:
df3['D'] = [2,4,6,8,10,12]
df3

A         B    C   D  E
2001-04-10  1.528961  1.528961  5.0   2  1
2001-04-11  0.511269  1.843507  5.0   4  2
2001-04-12  1.003140 -0.610323  5.0   6  3
2001-04-13 -0.198911 -1.170609  5.0   8  4
2001-04-14  0.285932 -0.453229  5.0  10  5
2001-04-15  1.639254  1.198057  5.0  12  6

In [48]:
# Seting using where
df3[df3>0] = -df3
df3

A         B    C   D  E
2001-04-10 -1.528961 -1.528961 -5.0  -2 -1
2001-04-11 -0.511269 -1.843507 -5.0  -4 -2
2001-04-12 -1.003140 -0.610323 -5.0  -6 -3
2001-04-13 -0.198911 -1.170609 -5.0  -8 -4
2001-04-14 -0.285932 -0.453229 -5.0 -10 -5
2001-04-15 -1.639254 -1.198057 -5.0 -12 -6

In [34]:
# Series is ndarray like
s1 = pd.Series(np.random.randn(5), index = ['a','b','c','d','e'])
s1

a    0.503459
b   -0.261824
c   -1.444666
d   -1.888507
e    0.521904
dtype: float64

In [52]:
s1[0]

-0.2554680421266063

In [53]:
s1[1:3]

b   -0.780920
c    0.428889
dtype: float64

In [54]:
s1[s1 > s1.mean()]

c    0.428889
e    1.430742
dtype: float64

In [55]:
s1.mean()

-0.0002944831150314631

In [56]:
s1[[1,3]]

b   -0.780920
d   -0.824714
dtype: float64

In [58]:
np.exp(s1)

a    0.774554
b    0.457984
c    1.535550
d    0.438360
e    4.181800
dtype: float64

In [61]:
# Converting to pandas array
s1.array

<PandasArray>
[-0.2554680421266063, -0.7809203898446431, 0.42888866873461234,
 -0.8247144687552334,   1.430741816416713]
Length: 5, dtype: float64

In [62]:
# Converting to numpy array
s1.to_numpy()
# Syntax of creating a numpy array : np.array([1,2,3],[4,5,6] np.int32)

array([-0.25546804, -0.78092039,  0.42888867, -0.82471447,  1.43074182])

In [90]:
array = np.array([[1,2,3],[4,5,6]], np.int32)
array

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# Series is dictionary like
s1['b']

-0.7809203898446431

In [64]:
s1['a'] = 5.555
s1

a    5.555000
b   -0.780920
c    0.428889
d   -0.824714
e    1.430742
dtype: float64

In [65]:
s1.get('d')

-0.8247144687552334

In [67]:
'e' in s1

True

In [68]:
'f' in s1

False

In [74]:
s1

a    5.555000
b   -0.780920
c    0.428889
d   -0.824714
e    1.430742
dtype: float64

In [78]:
s1[:] + s1[:-1]


a    11.110000
b    -1.561841
c     0.857777
d    -1.649429
e          NaN
dtype: float64

In [79]:
# Series have also name attribute
s2 = pd.Series(np.random.randn(3), name = 'spmething')
s2.name

'spmething'

In [80]:
s2 = pd.Series.rename('Another')

AttributeError: 'str' object has no attribute '_set_name'

In [81]:
s2.rename('Another')

0    0.290474
1    0.834345
2   -1.045768
Name: Another, dtype: float64

In [3]:
import pandas as pd
import numpy as np
# Creating a DataFrame
di = {'A':1.,
      'B':pd.Series([1,2,3,4,5] ,index = list(range(5)), dtype = 'float32'),
      'C':np.array([5]*5 ,dtype = 'int32'),
      'D':pd.Timestamp('20010410'),
      'E':pd.Categorical(['tree','branch','tree','branch','tree'])}
df = pd.DataFrame(di, index = list(range(10,15)))
df

A   B  C          D       E
10  1.0 NaN  5 2001-04-10    tree
11  1.0 NaN  5 2001-04-10  branch
12  1.0 NaN  5 2001-04-10    tree
13  1.0 NaN  5 2001-04-10  branch
14  1.0 NaN  5 2001-04-10    tree

In [5]:
s1 = pd.Series([1,2,3,4,5], index = list(range(5)), dtype = 'float32')
s1

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float32

In [16]:
# Creating a DataFrame from list of Dictionaries . The dics will act as rows and some of columns will be null
l1 = [{'a': 1, 'b': 2}, {'d': 5, 'b': 10, 'e': 20}]
s1 = pd.DataFrame(l1)
s1

a   b    d     e
0  1.0   2  NaN   NaN
1  NaN  10  5.0  20.0

In [26]:
# Swapping values
df[['A','B']] = df[['B','A']]
df

A    B  C          D       E
10 NaN  1.0  5 2001-04-10    tree
11 NaN  1.0  5 2001-04-10  branch
12 NaN  1.0  5 2001-04-10    tree
13 NaN  1.0  5 2001-04-10  branch
14 NaN  1.0  5 2001-04-10    tree

In [29]:
# Swapping values convinient method
df.loc[:,['A','B']] = df[['B','A']].to_numpy()
df

A   B  C          D       E
10  1.0 NaN  5 2001-04-10    tree
11  1.0 NaN  5 2001-04-10  branch
12  1.0 NaN  5 2001-04-10    tree
13  1.0 NaN  5 2001-04-10  branch
14  1.0 NaN  5 2001-04-10    tree

In [30]:
# You may access an index on a Series or column on a DataFrame directly as an attribute:
df.C

10    5
11    5
12    5
13    5
14    5
Name: C, dtype: int32

In [32]:
df['A'] = list(range(len(df.index)))
df

A   B  C          D       E
10  0 NaN  5 2001-04-10    tree
11  1 NaN  5 2001-04-10  branch
12  2 NaN  5 2001-04-10    tree
13  3 NaN  5 2001-04-10  branch
14  4 NaN  5 2001-04-10    tree

In [35]:
# using :: with series
s1

a    0.503459
b   -0.261824
c   -1.444666
d   -1.888507
e    0.521904
dtype: float64

In [36]:
s1[::2]

a    0.503459
c   -1.444666
e    0.521904
dtype: float64

In [38]:
s1[::3]

a    0.503459
d   -1.888507
dtype: float64

In [39]:
s1[::-1]

e    0.521904
d   -1.888507
c   -1.444666
b   -0.261824
a    0.503459
dtype: float64

In [40]:
s1[::-2]

e    0.521904
c   -1.444666
a    0.503459
dtype: float64